### PR TITLE
Actions

### PR DESCRIPTION
**Pull request by jburel**
This PR adds support for GHA
The deployment has been tested from my fork  and it is available under ome.staging
cc @dgault @joshmoore @sbesson

### CODE REVIEW

**Comment by jburel** [comment]
see https://github.com/jburel/ZarrReader/actions/runs/768274727

**Comment by joshmoore** [comment]
LGTM. @dgault, shall we try another tag when it's merged?

**Comment by dgault** [comment]
Actions look good, ill push another tag once I've got the tests included and merged

**Comment by jburel** [comment]
I will delete the test on artifatory so the tag does not get push my accident

**Comment by jburel** [comment]
tag removed from ome.staging

**Pull request merged**
