### PR TITLE
Add new option to list pixels in getUsedFiles

### PR DESCRIPTION
**Pull request by dgault**
This is a follow up to https://github.com/ome/ZarrReader/pull/41

As discussed, having an option to toggle if the chunk list is returned was the preffered approach. This PR reproduces the functionality of the previous noPixels effort, but also adds a new option (which can be set on MetadataOptions). The initial default is set to false, so no pixels files will be returned by default. This is for initial testing purposes and can be updated at a later date

### CODE REVIEW

**Comment by joshmoore** [comment]
Thanks, @dgault! @will-moore, let us know how this works for you.

**Comment by will-moore** [comment]
@joshmoore Currently documenting progress and questions at https://github.com/joshmoore/omero-mkngff/issues/2

**Comment by will-moore** [comment]
Updating on `pilot-idr0125`

```
$ sudo -u omero-server -s
$ wget https://merge-ci.openmicroscopy.org/jenkins/job/BIOFORMATS-build/default/lastSuccessfulBuild/artifact/bio-formats-build/ZarrReader/target/OMEZarrReader-0.3.2-SNAPSHOT-jar-with-dependencies.jar

$ mv OMEZarrReader-0.3.2-SNAPSHOT-jar-with-dependencies.jar OMEZarrReader.jar
$ rm /opt/omero/server/OMERO.server/lib/client/OMEZarrReader.jar
$ cp OMEZarrReader.jar /opt/omero/server/OMERO.server/lib/client/
$ rm /opt/omero/server/OMERO.server/lib/server/OMEZarrReader.jar
$ cp OMEZarrReader.jar /opt/omero/server/OMERO.server/lib/server/
```
```
$ sudo service omero-server restart
Redirecting to /bin/systemctl restart omero-server.service
```

**Comment by dgault** [comment]
Closing as option was not needed

**Pull request closed without merging**
