### PR TITLE
Bump to SNAPSHOT for merge build

### PR DESCRIPTION
**Pull request by joshmoore**
see: https://merge-ci.openmicroscopy.org/jenkins/job/BIOFORMATS-build/jdk=JDK8,label=testintegration/872/console

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-deploy-plugin:2.7:deploy (default-deploy) on project OMEZarrReader: Failed to deploy artifacts: Could not transfer artifact ome:OMEZarrReader:jar:0.0.1 from/to ome.staging (...nexus/repository/maven-internal/): Failed to transfer file: http://nexus:8081/nexus/repository/maven-internal/ome/OMEZarrReader/0.0.1/OMEZarrReader-0.0.1.jar. Return code is: 400, ReasonPhrase: Repository does not allow updating assets: maven-internal. -> [Help 1]
```

### CODE REVIEW

**Review by sbesson — APPROVED** [review]
Definitely good to have the merge build reminding us to put the HEAD of the branch at a SNAPSHOT version.

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [BIOFORMATS-push#965](https://merge-ci.openmicroscopy.org/jenkins/job/BIOFORMATS-push/965/). See the [console output](https://merge-ci.openmicroscopy.org/jenkins/job/BIOFORMATS-push/965/consoleText) for more details.
Possible conflicts:
  - PR #3 dgault 'ZarrReader: Add Unit tests'
    - pom.xml

--conflicts

**Comment by joshmoore** [comment]
@dgault @sbesson : thoughts welcome on the use of `bio-formats-tools` here. If we want to be more careful, I can put it in a profile and use `-Ptools` from `ome_zarr_test_suite`

**Comment by sbesson** [comment]
Is the intended worfklow tocompile this repository with `mvn` and be able to immediately invoke the command-line utilities?  Alternatively, I assume copying the JAR under the command-line tools bundle would work?

**Comment by joshmoore** [comment]
This is the script that I'm currently trying to get working:

```
#!/usr/bin/env bash
set -e
set -u
test -e ZarrReader  || git clone git://github.com/ome/ZarrReader 1>&2
cd ZarrReader
mvn package -DskipTests # 1>&2
cd ..
java -cp ZarrReader/target/*.jar loci.formats.tools.ImageInfo -nopix "$@"
```

**Comment by dgault** [comment]
I don't really like the idea of including tools here, it isn't needed anywhere for the reader itself and would defeat the purpose of having this as a separate repo. Just copying the jar doesn't work with the tools either, there is a need slight modification needed.

**Comment by joshmoore** [comment]
I'm not sure what you mean about the modification, but fair enough. I'll rollback the tools change and look into a script update that downloads tools from elsewhere.

**Comment by joshmoore** [comment]
see: https://github.com/ome/ome_zarr_test_suite/pull/16

**Comment by joshmoore** [comment]
Ok. Considering this is a bump to SNAPSHOT, merging so I can continue my testing. Next step is either to get the unit tests in or to get this released to artifactory.

**Pull request merged**
